name: Deploy

on:
  pull_request:
    branches: 
      - 'main'

jobs:
      deploy:
        name: Build, Deploy to S3 bucket
        runs-on: ubuntu-latest

        defaults:
          run:
            working-directory: ./frontend
    
        steps:
          - uses: actions/checkout@v2
    
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
              node-version: ${{ matrix.node-version }}
    
          - name: Install node packages
            run: yarn install
    
          - name: Build
            run: CI='' yarn build
    
          - name: S3 Sync
  uses: jakejarvis/s3-sync-action@v0.5.1

            with:
              args: --acl public-read --follow-symlinks --delete
            env:
              AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              AWS_REGION: ap-northeast-2
              SOURCE_DIR: 'frontend/build'